Remove code that causes $scope is not defined exception
ReferenceError: $scope is not defined
    at http://localhost:3000/scripts/angular/services.js:89:7
    at z (http://localhost:3000/components/angular/angular.min.js:93:5)
    at http://localhost:3000/components/angular/angular.min.js:94:173
    at h.$eval (http://localhost:3000/components/angular/angular.min.js:102:456)
    at h.$digest (http://localhost:3000/components/angular/angular.min.js:100:218)
    at h.$apply (http://localhost:3000/components/angular/angular.min.js:103:264)
    at f (http://localhost:3000/components/angular/angular.min.js:67:120)
    at F (http://localhost:3000/components/angular/angular.min.js:71:191)
    at XMLHttpRequest.x.onreadystatechange (http://localhost:3000/components/angular/angular.min.js:72:224)